// Generated by Wrangler on Sat Jun 15 2024 14:15:35 GMT+0200 (czas środkowoeuropejski letni)
// by running `wrangler types`

interface Env {
	TENANTID: string;
	CLIENTID: string;
	SUBSCRIPTIONID: string;
	CLIENTSECRET: string;
}
